### PR TITLE
feat: add nyc for test coverage

### PR DESCRIPTION
**Pull request by brettz9**
Builds on #2 and #3

- Linting: Use an eslint-recommended file-extension ("json") for `.eslintrc`
- Testing: Add `nyc` for checking coverage (and ignore unreached sanity guard)
- npm: Add `.npmignore` (for coverage-created .nyc_output and also to avoid `test` which uses devDep-only `eslint`)

### CODE REVIEW

**Comment by dpraul** [comment]
Excellent addition! Only suggestion is I see no reason to put testing & coverage in separate commands - can you just add `nyc` to the `test` command?

**Comment by brettz9** [comment]
Cool, done!

**Comment by brettz9** [comment]
I also added an npmignore as `.nyc_output` (and `test` with a call to the unpublished `eslint` package) would otherwise be included.

**Review by dpraul — APPROVED** [review]
Thanks for this as well!

**Pull request merged**
