### PR TITLE
feat: recommended config for easier usage

### PR DESCRIPTION
**Pull request by brettz9**
- Enhancement: Add `recommended` config for easier inclusion of plugin
- Maintenance: Add `.editorconfig` for automating proper IDE indenting
- Docs: Make indentation consistent across Markdown (2 sp. in
    README as with rules docs)

### CODE REVIEW

**Comment by dpraul** [comment]
Love it - especially the `recommended` config! It has always seemed odd to me to mix `editorconfig` and `eslint` though - are there IDEs that won't automatically apply your eslint rules as editor rules? I'm not against it, just never had the need for both personally.

**Comment by brettz9** [comment]
I've had trouble getting Atom to apply the eslint rules. I've tried https://atom.io/packages/eslint-tab-length , but IIRC, it sets the global tab preference, causing problems when switching between Atom tabs.

Maybe an issue could be filed with this Atom package to ensure the change was made on each tab switch rather than tab opening (if that was the issue). However, while `.editorconfig` presumably doesn't allow some of the sophisticated [options of the eslint rule](https://eslint.org/docs/rules/indent#options) (e.g., the context ones, such as https://eslint.org/docs/rules/indent#outeriifebody which I like), `.editorconfig` does have the additional advantage of being able to set different settings and apply them to different (including non-JavaScript) file types (which eslint would only do if it had a processor for that language, and then, it would only work on the JS portions, e.g., enforcing `indent` within the JS fenced blocks of Markdown).

A common case I run into for `.editorconfig` (beyond my lack of proper config in Atom to utilize `.eslintrc.*` indents) are README's using 4 spaces (it is a bit more readable), 2 spaces in `package.json` or `package-lock.json` (reformatting is automatically applied by npm, IIRC with indents as well, when running a local `npm i`, and I believe 2 spaces was the convention it enforces), and then whatever the project wants in their JavaScript, CSS, HTML, etc. (usually 2 spaces and sometimes 4 spaces and more rarely, tabs).

**Comment by dpraul** [comment]
> I've had trouble getting Atom to apply the eslint rules. I've tried https://atom.io/packages/eslint-tab-length , but IIRC, it sets the global tab preference, causing problems when switching between Atom tabs.
> 
> Maybe an issue could be filed with this Atom package to ensure the change was made on each tab switch rather than tab opening (if that was the issue). However, while `.editorconfig` presumably doesn't allow some of the sophisticated [options of the eslint rule](https://eslint.org/docs/rules/indent#options) (e.g., the context ones, such as https://eslint.org/docs/rules/indent#outeriifebody which I like), `.editorconfig` does have the additional advantage of being able to set different settings and apply them to different (including non-JavaScript) file types (which eslint would only do if it had a processor for that language, and then, it would only work on the JS portions, e.g., enforcing `indent` within the JS fenced blocks of Markdown).
> 
> A common case I run into for `.editorconfig` (beyond my lack of proper config in Atom to utilize `.eslintrc.*` indents) are README's using 4 spaces (it is a bit more readable), 2 spaces in `package.json` or `package-lock.json` (reformatting is automatically applied by npm, IIRC with indents as well, when running a local `npm i`, and I believe 2 spaces was the convention it enforces), and then whatever the project wants in their JavaScript, CSS, HTML, etc. (usually 2 spaces and sometimes 4 spaces and more rarely, tabs).

Thanks for the thorough explanation! Your points considered, I'm glad to include the `.editorconfig`. I believe you can rebase this off master now and it will no longer have to build off of #4

**Comment by brettz9** [comment]
I've rebased. On running a local npm install again, I get an update in one of the packages, so that's there too.

**Review by dpraul — APPROVED** [review]

**Comment by dpraul** [comment]
I saw that - normally I don't like including lockfile changes but this is small repo... I'll let this one through :)

Thanks for all the work you've done here! Most excited for this one - makes it much easier to use. I'll look to do a new release soon.

**Pull request merged**
